columns-api
sourcecoursepoc/source-course-orch pull request #4
Opened 2023-04-24 12:05 UTC by Keerthi-212839

2023-04-24 12:11 UTC, shijukbabu-ust requested changes

2023-04-24 12:11 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	        // You can use a service class to handle the business logic and create the response object
Where is it calling the project group service? 
Why the response is coded here. The response should be coming from config service.

2023-04-24 12:11 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +        String url = configServiceURL + "/projectGroups";
Check the URL of project group in config service and use the same here.

2023-04-24 14:16 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	        // You can use a service class to handle the business logic and create the response object
resolved

2023-04-24 14:16 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +        String url = configServiceURL + "/projectGroups";
resolved

2023-04-24 14:20 UTC, shijukbabu-ust requested changes

2023-04-24 14:20 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +        String url = configServiceURL + "/project";
Check the URL again in ProjectGroupController class in config service. The URL should match the URL in config service. Otherwise it wont connect. 
It should be `/project-groups`

2023-04-24 14:20 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +		        ResponseEntity<ProjectGroupResponse> responseList = new ResponseEntity<ProjectGroupResponse>(null);
Check the project controller and check how service is called.

2023-04-25 03:21 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	        // You can use a service class to handle the business logic and create the response object
resolved

2023-04-25 03:21 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +        String url = configServiceURL + "/projectGroups";
resolved

2023-04-25 03:21 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +		        ResponseEntity<ProjectGroupResponse> responseList = new ResponseEntity<ProjectGroupResponse>(null);
resolved

2023-04-25 03:21 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +        String url = configServiceURL + "/project";
resolved

2023-04-25 06:04 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +    @PostMapping("/project-groups")
Add this URL at class level in @RestController. So this will be common for other methods as well.

2023-04-25 06:15 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	        // You can use a service class to handle the business logic and create the response object
resolved

2023-04-25 06:16 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +    @PostMapping("/project-groups")
resolved

2023-04-25 06:22 UTC, shijukbabu-ust approved these changes

2023-04-25 06:23 UTC, merged