Columns api
sourcecoursepoc/source-course-orch pull request #5
Opened 2023-04-27 07:44 UTC by Keerthi-212839

2023-04-27 08:45 UTC, shijukbabu-ust requested changes

2023-04-27 08:45 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +import com.ust.sourcecourse.configuration.entity.Project;
Compilation is failing. Do not added configuration service as dependency in this orch service. 
Remove this import and in service classes as well.

2023-04-27 08:45 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +import com.ust.sourcecourse.configuration.entity.Project;
Compilation is failing. Do not added configuration service as dependency in this orch service. 
Do not ad entities & repository of other services here.

2023-04-27 09:22 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +import com.ust.sourcecourse.configuration.entity.Project;
resolved

2023-04-27 09:22 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +import com.ust.sourcecourse.configuration.entity.Project;
resolved

2023-04-27 09:39 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +import com.ust.sourcecourse.configuration.entity.Project;
resolved

2023-04-27 09:39 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +import com.ust.sourcecourse.configuration.entity.Project;
resolved

2023-04-27 11:02 UTC, shijukbabu-ust requested changes

2023-04-27 11:02 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +import com.ust.sourcecourse.configuration.entity.ProjectGroup;
Remove entity and repository imports

2023-04-27 11:02 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +@CrossOrigin(origins = "*", allowedHeaders = "*")
Add this line in ProjectController class also.

2023-04-27 11:42 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +import com.ust.sourcecourse.configuration.entity.ProjectGroup;
resolved

2023-04-27 11:43 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +@CrossOrigin(origins = "*", allowedHeaders = "*")
resolved

2023-04-27 12:48 UTC, shijukbabu-ust requested changes

2023-04-27 12:48 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	public ResponseEntity<List<ProjectGroupResponse>> createProjectGroup(
Check latest code in config service. It returns of type ProjectGroupResponse and not List<ProjectGroupResponse>

2023-04-27 12:48 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +		List<ProjectGroupResponse> projectGroups = (List<ProjectGroupResponse>) projectGroupService
The service return type is ResponseEntity<List<ProjectGroupResponse>>. Take as that type itself. Do not typecast.

2023-04-27 12:48 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +		if (!projectGroups.isEmpty()) {
This check is already done at Service class right? So no need to check here again. Directly return the result.

2023-04-27 12:48 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +            url, HttpMethod.POST, request, new ParameterizedTypeReference<List<ProjectGroupResponse>>() {
It should not be list.

2023-05-02 07:33 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +import com.ust.sourcecourse.configuration.entity.Project;
resolved

2023-05-02 07:33 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +import com.ust.sourcecourse.configuration.entity.Project;
resolved

2023-05-02 07:33 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +import com.ust.sourcecourse.configuration.entity.ProjectGroup;
resolved

2023-05-02 07:33 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +@CrossOrigin(origins = "*", allowedHeaders = "*")
resolved

2023-05-02 07:33 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	public ResponseEntity<List<ProjectGroupResponse>> createProjectGroup(
resolved

2023-05-02 07:33 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +		List<ProjectGroupResponse> projectGroups = (List<ProjectGroupResponse>) projectGroupService
resolved

2023-05-02 07:34 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +		if (!projectGroups.isEmpty()) {
resolved

2023-05-02 07:34 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	@GetMapping
resolved

2023-05-02 07:34 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	@PutMapping()
resolved

2023-05-02 07:35 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	@DeleteMapping
resolved

2023-05-02 07:35 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +            url, HttpMethod.POST, request, new ParameterizedTypeReference<List<ProjectGroupResponse>>() {
resolved

2023-05-02 07:35 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +    	String url = configServiceURL + "/project-groups/" + id  ;
resolved

2023-05-02 08:08 UTC, shijukbabu-ust requested changes

2023-05-02 08:08 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +        String url = configServiceURL + "Project group with uid ";
Why is this changed? It should be /project-groups

2023-05-02 08:08 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +        return ResponseEntity.status(responseEntity.getStatusCode()).body(responseEntity.getBody());    }
Directly u can return the responseEntity

2023-05-02 08:08 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	    List<ProjectGroupResponse> projectGroups = (List<ProjectGroupResponse>) projectGroupService.findByProjectUid(uid);
Why is it typecasting? The return type in service class is already ResponseEntity.

2023-05-02 08:08 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	@GetMapping("/{uid}")
Rename it to projectId and similarly change in Path variable as well.

2023-05-02 08:08 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	@PutMapping()
Add path variable groupUid

2023-05-02 08:08 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	@DeleteMapping
Add Path variable groupUid

2023-05-02 08:08 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +    	String url = configServiceURL + "/project-groups/" + id;
URL should be /project-groups/project/{projectId}

2023-05-02 08:08 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	@GetMapping("/{uid}")
URL should be /project/{projectId}

2023-05-02 12:39 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +import com.ust.sourcecourse.configuration.entity.Project;
resolved

2023-05-02 12:40 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +import com.ust.sourcecourse.configuration.entity.ProjectGroup;
resolved

2023-05-02 12:40 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +@CrossOrigin(origins = "*", allowedHeaders = "*")
resolved

2023-05-02 12:40 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	public ResponseEntity<List<ProjectGroupResponse>> createProjectGroup(
resolved

2023-05-02 12:40 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +		if (!projectGroups.isEmpty()) {
resolved

2023-05-02 12:40 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	@GetMapping
resolved

2023-05-02 12:41 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	@PutMapping()
resolved

2023-05-02 12:41 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	@DeleteMapping
resolved

2023-05-02 12:41 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +            url, HttpMethod.POST, request, new ParameterizedTypeReference<List<ProjectGroupResponse>>() {
resolved

2023-05-02 12:41 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +    	String url = configServiceURL + "/project-groups/" + id  ;
resolved

2023-05-02 12:41 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +        String url = configServiceURL + "Project group with uid ";
resolved

2023-05-02 12:41 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +        return ResponseEntity.status(responseEntity.getStatusCode()).body(responseEntity.getBody());    }
resolved

2023-05-02 12:41 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	    List<ProjectGroupResponse> projectGroups = (List<ProjectGroupResponse>) projectGroupService.findByProjectUid(uid);
resolved

2023-05-02 12:42 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	@PutMapping()
resolved

2023-05-02 12:42 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +	@DeleteMapping
resolved

2023-05-02 12:42 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/service/ProjectGroupService.java
> +    	String url = configServiceURL + "/project-groups/" + id;
resolved

2023-05-02 14:01 UTC, shijukbabu-ust requested changes

2023-05-02 14:17 UTC, shijukbabu-ust commented
Add get mapping for GroupUID as well.

2023-05-03 04:43 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +    @PostMapping("/project/{projectId}")
resolved

2023-05-03 04:43 UTC, Keerthi-212839 commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +    @PutMapping("/{uid}/{groupUid}")
resolved

2023-05-03 06:16 UTC, shijukbabu-ust requested changes

2023-05-03 06:16 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +    public ResponseEntity<List<ProjectGroupResponse>> getProjectGroupsByProjectUid(@PathVariable Long uid) {
Change variable name to `projectId` or Add as `@PathVariable("projectId")`

2023-05-03 06:16 UTC, shijukbabu-ust commented on src/main/java/com/ust/sourcecourse/orchestrator/controller/ProjectGroupController.java
> +    public ResponseEntity<ProjectGroupResponse> updateProjectGroup(@PathVariable Long uid, @PathVariable Long groupUid, @RequestBody ProjectGroupRequest projectGroupRequest) {
No need of uid variable

2023-05-03 06:46 UTC, shijukbabu-ust approved these changes

2023-05-03 06:46 UTC, merged